"""PR4.5: proves the audit_events consumer pipeline (parse_audit_event ->
Sink) needs no special-casing between the two real producers of
audit:events -- this repo's own AuditLogger, and omnibioai-api-gateway's
independent producer -- because both now emit the identical AuditEvent
contract.

`_gateway_shaped_payload` below is a hand-kept-in-sync mirror of
omnibioai-api-gateway/app/services/audit_client.py::build_audit_event()'s
actual output shape (that repo has no dependency on this one -- separate
deployables, no shared package -- so this is intentionally a parallel
definition, not an import). If that function's shape changes, this test
file must be updated to match, and its drift would surface here as a
sudden validation/assertion failure the next time both repos' test suites
are run -- which is the whole point of encoding the contract as an
executable fixture instead of only as prose in a report.
"""
import json
import uuid
from datetime import datetime, timezone

import pytest

from audit.models import AuditEvent
from consumers.processor import parse_audit_event
from consumers.sink import Sink
from db.models import AuditEventRecord


def _gateway_shaped_payload(**overrides) -> dict:
    """Mirrors build_audit_event()'s exact output shape and field-generation
    strategy (event_id/timestamp minted once, at emission time -- not left
    for this side to default)."""
    payload = {
        "event_id": str(uuid.uuid4()),
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "service": "gateway",
        "event_type": "request",
        "user_id": None,
        "action": "",
        "resource": None,
        "decision": None,
        "reason": None,
        "trace_id": None,
        "context": {},
    }
    payload.update(overrides)
    return json.dumps(payload)


# ---------------------------------------------------------------------------
# Gateway-shaped events pass through the worker's real parse + persist path
# ---------------------------------------------------------------------------

def test_gateway_request_event_parses_and_persists(db_session):
    raw = _gateway_shaped_payload(
        event_type="request",
        user_id="u1",
        action="GET /workbench/ping",
        decision="allow",
        trace_id="trace-1",
        context={"endpoint": "http://gw/workbench/ping", "latency_ms": 12, "status_code": 200},
    )

    event = parse_audit_event(raw)
    assert isinstance(event, AuditEvent)

    result = Sink(db_session).write(event.model_dump())
    assert result is True

    row = db_session.get(AuditEventRecord, event.event_id)
    assert row is not None
    assert row.service == "gateway"
    assert row.event_type == "request"
    assert row.context == {
        "endpoint": "http://gw/workbench/ping", "latency_ms": 12, "status_code": 200,
    }


@pytest.mark.parametrize("event_type,decision,reason,extra_context", [
    ("hpc_denied", "deny", "hpc_quota_exceeded", {}),
    ("auth_failed", "deny", "missing_token", {}),
    ("policy_denied", "deny", "policy_block", {}),
    ("upstream_forward", "allow", None, {"status_code": 200}),
    ("trace_created", None, None, {"path": "/workbench/run", "method": "POST"}),
])
def test_every_gateway_event_type_parses_and_persists(
    db_session, event_type, decision, reason, extra_context
):
    """All 5 distinct event_type values gateway actually emits (per its 7
    producer call sites) round-trip through the same consumer path."""
    raw = _gateway_shaped_payload(
        event_type=event_type,
        decision=decision,
        reason=reason,
        trace_id="trace-x",
        context=extra_context,
    )

    event = parse_audit_event(raw)
    result = Sink(db_session).write(event.model_dump())

    assert result is True
    row = db_session.get(AuditEventRecord, event.event_id)
    assert row.event_type == event_type
    assert row.context == extra_context


def test_gateway_event_id_and_timestamp_survive_the_pipeline_unchanged():
    """The PR4.5 fix's core guarantee: event_id/timestamp are minted by the
    producer (gateway) and must arrive at the consumer exactly as sent --
    not regenerated by AuditEvent's Field(default_factory=...) defaults,
    which would happen if the producer omitted these fields (the pre-PR4.5
    bug: a redelivered/retried message got a *different* event_id every
    parse, defeating Sink's dedup-on-event_id guarantee)."""
    original_id = str(uuid.uuid4())
    original_ts = "2026-03-01T10:00:00+00:00"
    raw = _gateway_shaped_payload(event_id=original_id, timestamp=original_ts)

    event = parse_audit_event(raw)

    assert event.event_id == original_id
    assert event.timestamp.isoformat() == original_ts


def test_gateway_event_redelivery_is_a_safe_noop_not_a_duplicate_row(db_session):
    """Simulates a worker crash/retry redelivering the same Redis message
    twice -- because event_id is now stable across the two parse attempts
    (previous test), the second write must be the same PR4.2 dedup-safe
    no-op a redelivered security-audit-native event already gets, not a
    second row."""
    raw = _gateway_shaped_payload(event_id=str(uuid.uuid4()))

    first_event = parse_audit_event(raw)
    second_event = parse_audit_event(raw)  # redelivered message, re-parsed
    assert first_event.event_id == second_event.event_id

    sink = Sink(db_session)
    assert sink.write(first_event.model_dump()) is True
    assert sink.write(second_event.model_dump()) is True

    count = (
        db_session.query(AuditEventRecord)
        .filter_by(event_id=first_event.event_id)
        .count()
    )
    assert count == 1


# ---------------------------------------------------------------------------
# security-audit's own events still persist (unaffected regression check)
# ---------------------------------------------------------------------------

def test_security_audit_native_event_still_persists(db_session):
    """A real AuditEvent, constructed the way AuditLogger.log() always has
    (PR4.1/4.1.5), must still parse and persist exactly as before -- PR4.5
    only reconciles the gateway producer, it must not touch this path."""
    native_event = AuditEvent(
        service="omnibioai-auth", event_type="auth_login", user_id="u1",
        action="login", decision="success",
    )
    raw = json.dumps(native_event.model_dump(mode="json"))

    parsed = parse_audit_event(raw)
    result = Sink(db_session).write(parsed.model_dump())

    assert result is True
    row = db_session.get(AuditEventRecord, native_event.event_id)
    assert row.service == "omnibioai-auth"


# ---------------------------------------------------------------------------
# No duplicate schema paths on the consumer side: one function, one code
# path, handles both producers -- no format-sniffing/branching needed.
# ---------------------------------------------------------------------------

def test_gateway_and_security_audit_events_use_the_identical_parse_function(db_session):
    """Both producer shapes go through the exact same parse_audit_event /
    Sink.write call with no producer-specific branch -- this test would
    fail to compile/run meaningfully if the two needed different handling,
    since it calls both through one shared helper."""

    def _round_trip(raw_json: str) -> AuditEventRecord:
        parsed = parse_audit_event(raw_json)
        Sink(db_session).write(parsed.model_dump())
        return db_session.get(AuditEventRecord, parsed.event_id)

    gateway_raw = _gateway_shaped_payload(event_type="request")
    native_raw = json.dumps(
        AuditEvent(service="policy", event_type="policy_decision").model_dump(mode="json")
    )

    gateway_row = _round_trip(gateway_raw)
    native_row = _round_trip(native_raw)

    assert gateway_row is not None
    assert native_row is not None
    assert gateway_row.event_id != native_row.event_id
